#:schema https://raw.githubusercontent.com/usecannon/cannon/refs/heads/dev/packages/lsp/src/schema.json
name = "cow-ethflow"
version = "1.0.3"

# dummy token for test network only
[import.dummyToken]
source = "mintable-token:2.0"
chainId = 13370

[import.cow]
source = "cow-settlement:2.0.2"

[var.main]
cowSettlement = "<%= cow.Settlement.address %>"

# WARNING: Make sure you override the wrappedNativeToken with the corresponding native token contract address in the network.
# The deployment of CoWSwapEthFlow needs to happen in nonce 0, so there's only one possible attempt.
wrappedNativeToken = "<%= dummyToken.Token.address %>"

deployerAccount = "0x18AA26D5e4A18ef6E49c509D52a4f7d60242b10D"

[deploy.EthFlow]
artifact = "CoWSwapEthFlow"

# EthFlow is one of the few CoW protocol contracts that doesn't use create2 because the `wrappedNativeToken`
# so to achieve the same address, we use the same deployment key at nonce 0, resulting in the same address
# no matter the initcode
from = "<%= settings.deployerAccount %>"
nonce = 0

args = ["<%= settings.cowSettlement %>", "<%= settings.wrappedNativeToken %>"]

# Prevent the contract from failing to deploy due to gas limit issues
overrides.gasLimit = "2000000"
