name: artifacts

on:
  push:
    branches: [main]
    tags:
      - "**"
      - "!**-artifacts"

env:
  FOUNDRY_PROFILE: ci

jobs:
  artifacts:
    name: Artifacts generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive

      # This step is required by `generate-artifacts.sh` since it pins an old
      # version of the Hardhat package ("hardhat@2.12.2").
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly

      - name: Generate artifacts and push as new tag
        run: bash .github/scripts/release-artifacts.sh "$GITHUB_REF"
